### ISSUE TITLE
技术询问：战斗技能 Ready 识别实际运行逻辑

### ISSUE THREAD

**Issue by Grapefruit9919** [MaaAssistantArknights/MaaAI#6]
readme中的 **Ready 识别 二分模型**仅能进行 **是/否** 的判断吧？
请问MAA实际运行中是先使用了yolo进行预检测，然后再分割为64x64 的图标进行检测的吗？为什么不直接用yolo？

**Comment by MistEO** [comment]
技能识别没用 yolo，干员的位置是已知的（都是 MAA 自己放的），做个固定偏移量的 ROI 然后跑二分模型

**Comment by MistEO** [comment]
那个 yolo 的检测模型现在只给 “视频识别” 功能用的

**Comment by Grapefruit9919** [comment]
> 技能识别没用 yolo，干员的位置是已知的（都是 MAA 自己放的），做个固定偏移量的 ROI 然后跑二分模型

原来如此！我忘了干员位置是自己设定的了，所以坐标直接偏移即可，非常感谢！
